package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;


public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);


    /**
     * 根据用户id和productId查询
     * */
    Cart selectCartByUserIdAndProductId(@Param("userId")Integer userId,
                                        @Param("productId")Integer productId);

    /**
     * 查询用的购物车信息
     * */
    List<Cart> selectCartByUserId(@Param("userId")Integer userId);


    /**
     * 统计用户购物信息是否全选
     * @return >0说明未全选
     * */
    int isCheckedAll(Integer userId);

    /**
     * 删除购物车的某些商品
     * */
    int deleteByUserAndProductIds(@Param("userId")Integer userId,
                                  @Param("productIdList")List<Integer> productIdList);


    /**
     * 操作购物车商品是否选中
     * check  1表示选中，0表示未选中
     * */
    int selectOrUnselectProduct(@Param("userId") Integer userId,
                                @Param("productId") Integer productId,
                                @Param("check") Integer check);



    /**
     * 统计用户购物车中产品数量
     * */
    int get_cart_product_count(Integer userId);

    /**
     * 查询购物车中用户已选中的信息
     * */
    List<Cart> findCartListByUserIdAndChecked(Integer userId);


    /**
     * 批量删除购物车商品
     * */
    int batchDelete(List<Cart> cartList);

}